#!/usr/bin/env node
/**
 * Patch the generated `android/` directory with build fixes that are lost
 * when `expo prebuild` regenerates the directory.
 *
 * Fixes applied (all idempotent — safe to run repeatedly):
 *   1. gradle-wrapper.properties → force Gradle 9.5.0 (9.7.1+ bundles Kotlin 2.4.0
 *      which is incompatible with RN/Expo plugins compiled against Kotlin 2.1.x)
 *   2. gradle.properties → add `-Xskip-metadata-version-check` to work around
 *      Kotlin runtime 2.4.0 vs compiler 2.1.20 metadata mismatch in included builds
 *   3. build.gradle → force `org.jetbrains:annotations:23.0.0` to resolve
 *      version conflicts between AGP and Kotlin plugin transitive dependencies
 *   4. node_modules/@react-native/gradle-plugin/settings.gradle.kts → remove
 *      foojay-resolver-convention 0.5.0 (requires Gradle 9.8+ for IBM_SEMERU)
 *   5. node_modules/@react-native/gradle-plugin sub-module build files:
 *      jvmToolchain(17) -> jvmToolchain(21) (4 modules hardcode Java 17;
 *      most dev machines only have JDK 21, which is backwards-compatible)
 *
 * The generated `android/` directory is gitignored (root .gitignore →
 * `apps/mobile/android/` is regenerated by `expo prebuild`). This script
 * lives in `apps/mobile/scripts/` and is git-tracked, so the fixes survive
 * across fresh checkouts.
 *
 * Usage: called automatically by the build:android:apk script chain, after
 * `expo prebuild` has generated the directory.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const mobileRoot = join(scriptDir, ".."); // apps/mobile
const androidDir = join(mobileRoot, "android");
const repoRoot = join(mobileRoot, "../.."); // repo root (pnpm workspace root)
const rnSettingsKts = join(
  repoRoot,
  "node_modules/@react-native/gradle-plugin/settings.gradle.kts",
);

if (!existsSync(androidDir)) {
  console.error(
    `[patch-gradle] android/ not found at ${androidDir}\n` +
      "Run `pnpm -C apps/mobile exec expo prebuild --platform android` first.",
  );
  process.exit(1);
}

let patched = 0;

// --- Fix 1: Gradle wrapper → 9.5.0 ---
{
  const p = join(androidDir, "gradle", "wrapper", "gradle-wrapper.properties");
  if (existsSync(p)) {
    let content = readFileSync(p, "utf8");
    const targetUrl = "https\\://services.gradle.org/distributions/gradle-9.5.0-bin.zip";
    if (!content.includes("gradle-9.5.0-bin.zip")) {
      content = content.replace(
        /distributionUrl=.*gradle-[\d.]+-bin\.zip/,
        `distributionUrl=${targetUrl}`,
      );
      writeFileSync(p, content);
      patched++;
      console.log("[patch-gradle] pinned Gradle wrapper to 9.5.0");
    }
  } else {
    console.warn("[patch-gradle] gradle-wrapper.properties not found, skipping fix 1");
  }
}

// --- Fix 2: gradle.properties → -Xskip-metadata-version-check + JDK paths ---
{
  const p = join(androidDir, "gradle.properties");
  if (existsSync(p)) {
    let content = readFileSync(p, "utf8");
    let changed = false;
    if (!content.includes("-Xskip-metadata-version-check")) {
      content +=
        "\n" +
        "# Workaround: Gradle 9.5.0+ bundles Kotlin 2.4.0 but the RN/Expo plugins\n" +
        "# use Kotlin 2.1.x compiler; skip the metadata version check.\n" +
        "kotlin.options.freeCompilerArgs=-Xskip-metadata-version-check\n";
      changed = true;
    }
    if (!content.includes("org.gradle.java.installations.paths")) {
      content +=
        "\n" +
        "# Point Gradle to locally installed JDKs so toolchains can be resolved\n" +
        "# without foojay-resolver (which requires Gradle 9.8+).\n" +
        "org.gradle.java.installations.paths=D:/Scoop/apps/temurin17-jdk/current,D:/IDEA/JDK21.0.4\n";
      changed = true;
    }
    if (changed) {
      writeFileSync(p, content);
      patched++;
      console.log("[patch-gradle] added compiler args + JDK paths to gradle.properties");
    }
  } else {
    console.warn("[patch-gradle] gradle.properties not found, skipping fix 2");
  }
}

// --- Fix 3: root build.gradle → force org.jetbrains:annotations:23.0.0 ---
{
  const p = join(androidDir, "build.gradle");
  if (existsSync(p)) {
    let content = readFileSync(p, "utf8");
    if (!content.includes("force 'org.jetbrains:annotations:23.0.0'")) {
      // Insert resolutionStrategy block inside allprojects { repositories { ... } }
      // The generated build.gradle has an `allprojects` block with `repositories`.
      // We add a `configurations.all { resolutionStrategy { force ... } }` block.
      const marker = "allprojects {";
      const idx = content.indexOf(marker);
      if (idx < 0) {
        console.warn("[patch-gradle] could not find 'allprojects' block in build.gradle, skipping fix 3");
      } else {
        // Find the closing brace of the allprojects block
        // Insert after the closing brace of repositories within allprojects
        const afterAllprojects = content.indexOf("}", idx + marker.length + 1);
        // More robust: find the block and insert resolutionStrategy after repositories
        const insertion = `
  configurations.all {
    resolutionStrategy {
      force 'org.jetbrains:annotations:23.0.0'
    }
  }`;
        // Find where repositories block closes inside allprojects
        const reposBlockEnd = content.indexOf("}", idx + marker.length);
        // Actually, let's just find the line after the repositories closing and insert
        // Simpler approach: insert before the closing } of allprojects
        // Find the end of allprojects block
        let braceCount = 0;
        let allprojectsEnd = -1;
        for (let i = idx + marker.length; i < content.length; i++) {
          if (content[i] === "{") braceCount++;
          if (content[i] === "}") {
            braceCount--;
            if (braceCount === 0) {
              allprojectsEnd = i;
              break;
            }
          }
        }
        if (allprojectsEnd > 0) {
          content =
            content.slice(0, allprojectsEnd) +
            insertion +
            "\n" +
            content.slice(allprojectsEnd);
          writeFileSync(p, content);
          patched++;
          console.log("[patch-gradle] added annotations:23.0.0 force to build.gradle");
        } else {
          console.warn("[patch-gradle] could not locate end of allprojects block, skipping fix 3");
        }
      }
    }
  } else {
    console.warn("[patch-gradle] build.gradle not found, skipping fix 3");
  }
}

// --- Fix 4: RN settings.gradle.kts -> remove foojay-resolver-convention ---
{
  if (existsSync(rnSettingsKts)) {
    let content = readFileSync(rnSettingsKts, "utf8");
    if (content.includes("foojay-resolver-convention")) {
      content = content.replace(
        /plugins\s*\{[^}]*foojay-resolver-convention[^}]*\}/,
        "// foojay-resolver removed: requires Gradle 9.8+ (IBM_SEMERU), incompatible with pinned 9.5.0",
      );
      writeFileSync(rnSettingsKts, content);
      patched++;
      console.log("[patch-gradle] removed foojay-resolver from RN settings.gradle.kts");
    }
  } else {
    console.warn("[patch-gradle] RN settings.gradle.kts not found, skipping fix 4");
  }
}

// --- Fix 5: RN included build → jvmToolchain(17) → jvmToolchain(21) ---
// RN 0.83.6 hardcodes jvmToolchain(17) in 4 included-build modules. Most
// dev machines only have JDK 21; 21 is backwards-compatible with 17 code.
{
  const rnPluginDir = join(
    repoRoot,
    "node_modules/@react-native/gradle-plugin",
  );
  const buildFiles = [
    "react-native-gradle-plugin/build.gradle.kts",
    "settings-plugin/build.gradle.kts",
    "shared/build.gradle.kts",
    "shared-testutil/build.gradle.kts",
  ];
  for (const relPath of buildFiles) {
    const p = join(rnPluginDir, relPath);
    if (existsSync(p)) {
      let c = readFileSync(p, "utf8");
      if (c.includes("jvmToolchain(17)")) {
        c = c.replace(/jvmToolchain\(17\)/g, "jvmToolchain(21)");
        writeFileSync(p, c);
        patched++;
        console.log(`[patch-gradle] jvmToolchain 17->21 in ${relPath}`);
      }
    }
  }
}

// --- Fix 6: Add JDK installation paths for toolchain resolution ---
// The app build.gradle may require Java 17 toolchain while included builds
// use jvmToolchain(21). Add org.gradle.java.installations.paths to the
// global ~/.gradle/gradle.properties so all builds can find both JDKs.
{
  const globalGradleProps = join(
    process.env.USERPROFILE || process.env.HOME,
    ".gradle",
    "gradle.properties",
  );
  const jdkPaths = "D:/Scoop/apps/temurin17-jdk/current,D:/IDEA/JDK21.0.4";
  if (existsSync(globalGradleProps)) {
    let c = readFileSync(globalGradleProps, "utf8");
    if (!c.includes("org.gradle.java.installations.paths")) {
      c += `\n# Auto-added by patch-gradle: JDK paths for toolchain resolution\norg.gradle.java.installations.paths=${jdkPaths}\n`;
      writeFileSync(globalGradleProps, c);
      patched++;
      console.log("[patch-gradle] added JDK paths to global gradle.properties");
    } else {
      console.log("[patch-gradle] global gradle.properties already has JDK paths");
    }
  } else {
    const dir = dirname(globalGradleProps);
    if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
    writeFileSync(
      globalGradleProps,
      `# Auto-added by patch-gradle: JDK paths for toolchain resolution\norg.gradle.java.installations.paths=${jdkPaths}\n`,
    );
    patched++;
    console.log("[patch-gradle] created global gradle.properties with JDK paths");
  }
}

// Also clean up any stale tasks.withType blocks from previous fix 6 iterations
{
  const p = join(androidDir, "app", "build.gradle");
  if (existsSync(p)) {
    let c = readFileSync(p, "utf8");
    const cleanPattern = /\n\n?\/\/ Pinned to JDK 21.*?\}\n\s*\}\n\s*\}\n?\s*\}\n/g;
    const tasksWithPattern = /\n+\/\/ Pinned to JDK 21.*$/s;
    if (cleanPattern.test(c) || tasksWithPattern.test(c)) {
      c = c.replace(tasksWithPattern, "").trimEnd() + "\n";
      writeFileSync(p, c);
      patched++;
      console.log("[patch-gradle] removed stale tasks.withType block from app/build.gradle");
    }
  }
}

console.log(
  `[patch-gradle] ${patched} fix(es) applied, ${6 - patched} already in place.`,
);