#!/usr/bin/env node
/**
 * Patch the generated `android/` directory with build fixes that are lost
 * when `expo prebuild` regenerates the directory.
 *
 * Fixes applied (all idempotent — safe to run repeatedly):
 *   1. gradle-wrapper.properties → force Gradle 9.5.0 (9.7.1+ bundles Kotlin 2.4.0
 *      which is incompatible with RN/Expo plugins compiled against Kotlin 2.1.x)
 *   2. gradle.properties → add `-Xskip-metadata-version-check` to work around
 *      Kotlin runtime 2.4.0 vs compiler 2.1.20 metadata mismatch in included builds
 *   3. build.gradle → force `org.jetbrains:annotations:23.0.0` to resolve
 *      version conflicts between AGP and Kotlin plugin transitive dependencies
 *
 * The generated `android/` directory is gitignored (root .gitignore →
 * `apps/mobile/android/` is regenerated by `expo prebuild`). This script
 * lives in `apps/mobile/scripts/` and is git-tracked, so the fixes survive
 * across fresh checkouts.
 *
 * Usage: called automatically by the build:android:apk script chain, after
 * `expo prebuild` has generated the directory.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const mobileRoot = join(scriptDir, ".."); // apps/mobile
const androidDir = join(mobileRoot, "android");

if (!existsSync(androidDir)) {
  console.error(
    `[patch-gradle] android/ not found at ${androidDir}\n` +
      "Run `pnpm -C apps/mobile exec expo prebuild --platform android` first.",
  );
  process.exit(1);
}

let patched = 0;

// --- Fix 1: Gradle wrapper → 9.5.0 ---
{
  const p = join(androidDir, "gradle", "wrapper", "gradle-wrapper.properties");
  if (existsSync(p)) {
    let content = readFileSync(p, "utf8");
    const targetUrl = "https\\://services.gradle.org/distributions/gradle-9.5.0-bin.zip";
    if (!content.includes("gradle-9.5.0-bin.zip")) {
      content = content.replace(
        /distributionUrl=.*gradle-[\d.]+-bin\.zip/,
        `distributionUrl=${targetUrl}`,
      );
      writeFileSync(p, content);
      patched++;
      console.log("[patch-gradle] pinned Gradle wrapper to 9.5.0");
    }
  } else {
    console.warn("[patch-gradle] gradle-wrapper.properties not found, skipping fix 1");
  }
}

// --- Fix 2: gradle.properties → -Xskip-metadata-version-check ---
{
  const p = join(androidDir, "gradle.properties");
  if (existsSync(p)) {
    let content = readFileSync(p, "utf8");
    if (!content.includes("-Xskip-metadata-version-check")) {
      content +=
        "\n" +
        "# Workaround: Gradle 9.5.0+ bundles Kotlin 2.4.0 but the RN/Expo plugins\n" +
        "# use Kotlin 2.1.x compiler; skip the metadata version check.\n" +
        "kotlin.options.freeCompilerArgs=-Xskip-metadata-version-check\n";
      writeFileSync(p, content);
      patched++;
      console.log("[patch-gradle] added -Xskip-metadata-version-check to gradle.properties");
    }
  } else {
    console.warn("[patch-gradle] gradle.properties not found, skipping fix 2");
  }
}

// --- Fix 3: root build.gradle → force org.jetbrains:annotations:23.0.0 ---
{
  const p = join(androidDir, "build.gradle");
  if (existsSync(p)) {
    let content = readFileSync(p, "utf8");
    if (!content.includes("force 'org.jetbrains:annotations:23.0.0'")) {
      // Insert resolutionStrategy block inside allprojects { repositories { ... } }
      // The generated build.gradle has an `allprojects` block with `repositories`.
      // We add a `configurations.all { resolutionStrategy { force ... } }` block.
      const marker = "allprojects {";
      const idx = content.indexOf(marker);
      if (idx < 0) {
        console.warn("[patch-gradle] could not find 'allprojects' block in build.gradle, skipping fix 3");
      } else {
        // Find the closing brace of the allprojects block
        // Insert after the closing brace of repositories within allprojects
        const afterAllprojects = content.indexOf("}", idx + marker.length + 1);
        // More robust: find the block and insert resolutionStrategy after repositories
        const insertion = `
  configurations.all {
    resolutionStrategy {
      force 'org.jetbrains:annotations:23.0.0'
    }
  }`;
        // Find where repositories block closes inside allprojects
        const reposBlockEnd = content.indexOf("}", idx + marker.length);
        // Actually, let's just find the line after the repositories closing and insert
        // Simpler approach: insert before the closing } of allprojects
        // Find the end of allprojects block
        let braceCount = 0;
        let allprojectsEnd = -1;
        for (let i = idx + marker.length; i < content.length; i++) {
          if (content[i] === "{") braceCount++;
          if (content[i] === "}") {
            braceCount--;
            if (braceCount === 0) {
              allprojectsEnd = i;
              break;
            }
          }
        }
        if (allprojectsEnd > 0) {
          content =
            content.slice(0, allprojectsEnd) +
            insertion +
            "\n" +
            content.slice(allprojectsEnd);
          writeFileSync(p, content);
          patched++;
          console.log("[patch-gradle] added annotations:23.0.0 force to build.gradle");
        } else {
          console.warn("[patch-gradle] could not locate end of allprojects block, skipping fix 3");
        }
      }
    }
  } else {
    console.warn("[patch-gradle] build.gradle not found, skipping fix 3");
  }
}

console.log(
  `[patch-gradle] ${patched} fix(es) applied, ${3 - patched} already in place.`,
);
